app/Http/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register all of the routes for an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the controller to call when that URI is requested.
  |
 */
Route::get('/', function () {

    return view('welcome');
});
Route::group(['namespace' => 'Api', 'prefix' => 'api'], function() {
    Route::get('get-all-cms', ['uses' => 'ApiController@getAllCms']);
    Route::get('get-all-settings ', ['uses' => 'ApiController@getAllsettings']);
    Route::get('get-cms-page-detail/{slug}', ['uses' => 'ApiController@getCmsDetail']);
    Route::get('get-all-category-for-menu', ['uses' => 'ApiController@getAllCategoryForMenu']);
    Route::get('get-slider', ['uses' => 'ApiController@getSlider']);
    Route::get('get-faq', ['uses' => 'ApiController@getfaq']);
    Route::post('login', ['uses' => 'ApiController@login']);
    Route::post('sign-up', ['uses' => 'ApiController@singUp']);
    Route::post('contact-us', ['uses' => 'ApiController@contactUs']);
    Route::post('forgot-password', ['uses' => 'ApiController@sendPasswordLink']);
    Route::get('check-socail-login/{token}', ['uses' => 'ApiController@checkSocailLogin']);
    Route::get('check-reset-password/{email_token}', ['uses' => 'ApiController@checkResetPassword']);
    Route::post('save-reset-password', ['uses' => 'ApiController@resetPasswordUpdate']);
    Route::post('get-product-by-category/{slug}', ['uses' => 'ApiController@getProductBycategory']);
    Route::post('get-search-product/{slug}', ['uses' => 'ApiController@getSearchProduct']);

    Route::get('get-category-attribute/{slug}', ['uses' => 'ApiController@getCategoryAttribute']);
    Route::get('get-all-attribute/{slug}', ['uses' => 'ApiController@getAllAttribute']);
   
   
//    Route::get('get-product-detail/{slug}', ['uses' => 'ApiController@getProductDetail']);
    Route::post('get-product-detail', ['uses' => 'ApiController@getProductDetail']);
    Route::get('get-user-detail/{id}/{token}', ['uses' => 'ApiController@getUserDetail']);
    Route::get('get-user-details/{id}/{token}', ['uses' => 'ApiController@getUserDetails']);

    Route::get('get-all-block', ['uses' => 'ApiController@getAllBlock']);
    Route::get('get-user-address/{id}/{token}', ['uses' => 'ApiController@getUserAddressBook']);

    
Route::post('update-profile', ['uses' => 'ApiController@updateProfile']);
Route::get('get-user-address/{id}/{token}', ['uses' => 'ApiController@getUserAddressBook']);
Route::post('save-address', ['uses' => 'ApiController@saveUserAddress']);
Route::post('set-address-default', ['uses' => 'ApiController@setAddressDefault']);
Route::get('delete-address/{id}/{user_id}', ['uses' => 'ApiController@deleteAddress']);
    Route::post('mobile-verify', ['uses' => 'ApiController@VarifyNumber']);
    Route::post('mobile-number-update', ['uses' => 'ApiController@UpdatePhoneNumber']);
    Route::get('resend-otp-password/{id}', ['uses' => 'ApiController@resendOtpPassword']);
    Route::post('social-signup/{type}', ['uses' => 'ApiController@socialSignup']);
    Route::post('update-address', ['uses' => 'ApiController@updateUserAddress']);
    Route::post('change-password', ['uses' => 'ApiController@changePassword']);
    Route::post('add-cart', ['uses' => 'ApiController@addToCart']);
    Route::get('get-cart/{user_id}', ['uses' => 'ApiController@getCartProduct']);
    Route::get('get-cart-item/{user_id}/{coupan_code?}', ['uses' => 'ApiController@getCartProductItem']);
    Route::post('update-cart', ['uses' => 'ApiController@updateCart']);
    Route::post('remove-cart', ['uses' => 'ApiController@removeCart']);
    Route::post('add-wishlist', ['uses' => 'ApiController@addToWishlist']);
    Route::get('get-wishlist/{user_id}', ['uses' => 'ApiController@getWishlistProfile']);
    Route::post('get-product-wishlist', ['uses' => 'ApiController@getProductWishlist']);
    Route::post('remove-wishlist', ['uses' => 'ApiController@removeWishlist']);
     Route::get('get-pincode-detail/{pin_code}', ['uses' => 'ApiController@getPincodeDetail']);
     Route::get('get-pincode-avalability/{pin_code}', ['uses' => 'ApiController@getPincodeAvalability']);
     Route::get('check-coupon-code/{user_id}/{coupon_code}', ['uses' => 'ApiController@checkCouponCode']);
     Route::post('payment/', ['uses' => 'ApiController@payment']);
     Route::post('payment-success/{order_id}/{payment_mode}', ['uses' => 'ApiController@paymentsuccess']);
     Route::get('get-order/{user_id}', ['uses' => 'ApiController@getOrder']);
     Route::post('order-cancel/{order_id}/{user_id}', ['uses' => 'ApiController@orderCancel']);
     Route::post('wallet-balance/{user_id}', ['uses' => 'ApiController@walletBalance']);
     Route::get('get-order-detail/{user_id}/{order_id}', ['uses' => 'ApiController@orderDdetail']);
     Route::get('get-wallet/{user_id}', ['uses' => 'ApiController@getWalletData']);
     Route::get('check-address-number/{user_id}', ['uses' => 'ApiController@checkAddressNumber']);
     Route::get('resend-otp-cod-mobile-number/{user_id}', ['uses' => 'ApiController@resendOtpCodPhoneNumber']);
     Route::post('cod-mobile-verify/{user_id}', ['uses' => 'ApiController@codVarifyNumber']);
     Route::post('newslatter', ['uses' => 'ApiController@newslatter']);

});

Route::group(['namespace' => 'Front'], function() {

    Route::get('facebook-login', ['uses' => 'PagesController@facebbok_redirect']);
    Route::get('facebook-callback', ['uses' => 'PagesController@facebook_callback']);
    Route::get('email-varified/{activation_key}', ['as' => 'admin.activation', 'uses' => 'PagesController@userActivation']);
    Route::get('send-mail-from-temp', ['uses' => 'CronController@sendMailFromTemp']);
    Route::get('chack-order-status', ['uses' => 'CronController@orderStatus']);
    Route::get('check-payment-status', ['uses' => 'CronController@checkPaymentStatus']);
    Route::get('send-invoice', ['uses' => 'CronController@sendInvoice']);
});


Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function() {

    Route::group(['middleware' => 'IsNotAuthenticated'], function() {

        Route::get('login', function() {
            return View::make('home');
        });
        Route::get('login', ['as' => 'admin.login', 'uses' => 'AuthController@getLogin']);
        Route::post('login', ['as' => 'admin.login', 'uses' => 'AuthController@postLogin']);
        Route::get('forgot-password', ['as' => 'admin.forgot_password', 'uses' => 'UsersController@forgotPassword']);

        Route::post('forgot-password', ['as' => 'admin.forgot_password', 'uses' => 'UsersController@sendPasswordLink']);
        Route::get('reset-password/{email_token}', ['as' => 'admin.reset_password', 'uses' => 'UsersController@resetPassword']);
        Route::post('reset-password/{email_token}', ['as' => 'admin.reset_password', 'uses' => 'UsersController@resetPasswordUpdate']);
    });

    Route::group(['middleware' => 'auth.admin'], function() {
        Route::resource('users', 'UsersController');
        Route::get('user-status-change/{id}/{status}', ['as' => 'admin.users.status_change', 'uses' => 'UsersController@status_change']);
        Route::get('user-email_verify/{id}/{email_verify}', ['as' => 'admin.users.email_verify', 'uses' => 'UsersController@email_verify']);
        Route::get('send-credentials/{id}', ['as' => 'admin.users.send_credentials', 'uses' => 'UsersController@sendCredentials']);
        Route::get('view-users/{id}', ['as' => 'admin.users.view', 'uses' => 'UsersController@view']);


        Route::resource('cms', 'CmsController');
        Route::resource('emailtemplates', 'EmailtemplatesController');
        Route::get('cms-status-change/{id}/{status}', ['as' => 'admin.cms.status_change', 'uses' => 'CmsController@status_change']);
        Route::get('profile', ['as' => 'admin.profile', 'uses' => 'UsersController@profile']);
        Route::post('profile', ['as' => 'admin.updateProfile', 'uses' => 'UsersController@updateProfile']);
        Route::get('change-password', ['as' => 'admin.ChangePassword', 'uses' => 'UsersController@ChangePassword']);
        Route::post('change-password', ['as' => 'admin.UpdateChangePassword', 'uses' => 'UsersController@UpdateChangePassword']);
        Route::resource('settings', 'SettingsController');
        Route::resource('dashboard', 'PagesController');
        Route::resource('emaillogs', 'EmailLogsController');
        Route::get('view-emaillogs/{id}', ['as' => 'admin.view_emaillogs', 'uses' => 'EmailLogsController@view']);

        // Route::get('/', 'PagesController@index');
        Route::get('logout', ['as' => 'admin.logout', 'uses' => 'AuthController@getLogout']);
        Route::get('/', ['as' => 'dashboard', 'uses' => 'PagesController@index']);
        Route::get('/newlatters', ['as' => 'newlatters', 'uses' => 'PagesController@newlatters']);
        Route::get('/newlatter-delete/{id}', ['as' => 'delete_newlatter', 'uses' => 'PagesController@delete_newlatter']);

        Route::get('upload-ckeditor-images', ['as' => 'upload_ckeditor_images', 'uses' => 'PagesController@uploadCkeditorImages']);

        ////////////////////***********Tags Controller************//////////////////////////////////////////////

        Route::resource('tags', 'TagsController');
        Route::get('tags-status-change/{id}/{status}', ['as' => 'admin.tags.status_change', 'uses' => 'TagsController@status_change']);

        // Category routing 
        /* Route::resource('category', 'CategoryController', [
          'except' => ['index', 'show','create','edit','update']
          ]); */
        Route::get('category/{id?}', ['as' => 'admin.category.index', 'uses' => 'CategoryController@index']);
        Route::get('edit-category/{id}/{parent_id?}', ['as' => 'admin.category.edit', 'uses' => 'CategoryController@edit']);

resources/views/includes/admin/breadcrumb.blade.php
@if(isset($breadcrumb))
  <ol class="breadcrumb">
 @foreach($breadcrumb['pages'] as $key=>$pages)


  		@if(is_array($pages))

	     <li>  {!!  Html::decode(Html::linkAsset(route($pages[0],$pages[1]), $key)) !!}</li>
	     @else
	     <li>  {!!  Html::decode(Html::linkAsset(route($pages), $key)) !!}</li>
	     @endif
@endforeach
       


   <li class="active">{{ $breadcrumb['active'] }}</li>
         </ol>
@endif

resources/views/includes/admin/file_upload_info.blade.php
   <div class="callout callout-info ">
                
                <ul>
                <li> {{trans('admin.ALLOW_IMAGE_TYPE')  }} &nbsp; {{ config('global.image_mime_type') }} </li>
                <li> {{trans('admin.MAX_UPLOAD_FILE_SIZE')  }} &nbsp; {{ config('global.upload_file_size') }} </li>

                
                  @if(isset($filecount))
                
             				   <li> {{trans('admin.MAXIMUM :FILECOUNT FILES_ARE_ALLOWED_TO_BE_UPLOADED', ['FILECOUNT' => config('global.max_file_count_upload')]) }} </li>
        			 @endif
                                <li> {{trans('admin.LARGE_FILES_MAY_TAKE_SOME_TIME')  }}  </li>
                </ul>
    </div>

resources/views/includes/admin/footer.blade.php
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    
  </div>
  <strong>   {{config('settings.CONFIG_COPYRIGHT')}}</strong> 
</footer>

resources/views/includes/admin/head.blade.php
<head>
  <meta charset="UTF-8" name="csrf-token" content="{{ csrf_token() }}">
  <title>{{
     isset($title) ? config('settings.CONFIG_SITE_TITLE')." :: ".$title : config('settings.CONFIG_SITE_TITLE') }}
  </title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
     <link rel="shortcut icon" href="{{ asset('img/favicon.png') }}">
  <!-- Bootstrap 3.3.4 -->
  {!! Html::style( asset('admin/bootstrap/css/bootstrap.min.css')) !!}
  {!! Html::style( asset('css/font-awesome.css')) !!}
  {!! Html::style( asset('css/ionicons.css')) !!}
  <!-- FontAwesome 4.3.0 
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
  -->
  <!-- Ionicons 2.0.0 
  <link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
  -->
  <!-- Theme style -->

  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->



  <!-- iCheck -->
  {!! Html::style( asset('admin/plugins/iCheck/flat/blue.css')) !!}
  <!-- Morris chart -->


  <!-- Date Picker -->
  {!! Html::style( asset('admin/plugins/datepicker/datepicker3.css')) !!}
  <!-- Daterange picker -->
  {!! Html::style( asset('admin/plugins/daterangepicker/daterangepicker-bs3.css')) !!}
  <!-- bootstrap wysihtml5 - text editor -->
  
  
  <!-- Select2 -->
  {!! Html::style( asset('admin/plugins/select2/select2.min.css')) !!}
 

  <!-- Bootstrap time Picker -->
  {!! Html::style( asset('admin/plugins/timepicker/bootstrap-timepicker.min.css')) !!}
  {!! Html::style( asset('css/bootstrap-multiselect.css')) !!}
  <!-- iCheck for checkboxes and radio inputs -->
  {!! Html::style( asset('admin/plugins/iCheck/all.css')) !!}
    {!! Html::style( asset('admin/css/jquery.noty.css')) !!}
  {!! Html::style( asset('admin/css/noty_theme_default.css')) !!}
    {!! Html::style( asset('admin/dist/css/AdminLTE.min.css')) !!}
      {!! Html::style( asset('admin/dist/css/skins/_all-skins.min.css')) !!}
      {!! Html::style( asset('admin/css/custom.css')) !!}
 
  
<!-- jQuery 2.1.4 -->
{!! Html::script( asset('admin/plugins/jQuery/jQuery-2.1.4.min.js')) !!}
{!! Html::script( asset('js/jquery-ui.min.js')) !!}
<!-- jQuery UI 1.11.4 -->


<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script type="text/javascript">

  var IMAGE_URL   =   "{!! WEBSITE_ADMIN_IMG_URL !!}";
  var WEBSITE_ADMIN_URL   =   "{!! WEBSITE_ADMIN_URL !!}";
  var WEBSITE_URL   =   "{!! WEBSITE_URL !!}";
  var csrf_token          = "{{ csrf_token()}}";
  var date_format          = "{{ DATE_FORMATE_JS }}";
  var CONFIG_ALLOWED_IMAGE_TYPE          = "{{ config('global.image_mime_type') }}";
  var UPLOAD_FILE_SIZE_IMAGE          = {{ config('global.file_max_upload_size') }};
  var MAX_FILE_COUNT_UPLOAD          = {{ config('global.max_file_count_upload') }};

</script>
<!-- Bootstrap 3.3.2 JS -->
{!! Html::script(asset('admin/bootstrap/js/bootstrap.min.js')) !!}
{!! Html::script(asset('js/jquery.noty.js')) !!}
{!! Html::script(asset('js/jquery.blockUI.js')) !!}
<!-- Morris.js charts -->

{!! Html::script( asset('admin/plugins/daterangepicker/daterangepicker.js')) !!}
<!-- datepicker -->
{!! Html::script( asset('admin/plugins/datepicker/bootstrap-datepicker.js')) !!}
<!-- Bootstrap WYSIHTML5 -->
{!! Html::script( asset('ckeditor/ckeditor.js')) !!}
{!! Html::script( asset('ckeditor/config.js')) !!}
<!-- Slimscroll -->
{!! Html::script( asset('admin/plugins/slimScroll/jquery.slimscroll.min.js')) !!}

<!-- adminLTE App -->
{!! Html::script( asset('admin/dist/js/app.min.js')) !!}
<!-- Select2 -->
{!! Html::script( asset('admin/plugins/select2/select2.full.min.js')) !!}
<!-- date-range-picker -->

{!! Html::script( asset('admin/plugins/daterangepicker/daterangepicker.js')) !!}
<!-- bootstrap time picker -->
{!! Html::script( asset('admin/plugins/timepicker/bootstrap-timepicker.min.js')) !!}
<!-- bootstrap color picker -->
{!! Html::script( asset('admin/plugins/colorpicker/bootstrap-colorpicker.min.js')) !!}


<!-- iCheck 1.0.1 -->
{!! Html::script( asset('admin/plugins/iCheck/icheck.min.js')) !!}
{!! Html::script( asset('admin/js/bootbox.min.js')) !!}
{!! Html::script( asset('js/bootstrap-multiselect.js')) !!}
<!-- AdminLTE for demo purposes -->
{!! Html::script( asset('admin/dist/js/demo.js')) !!}
{!! Html::script( asset('admin/js/global.js')) !!}

<!-- Page script -->
<script>
    
    

    $(function () {

$.ajaxSetup({
    headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    }
})
      
       if($('#edit-editor-content').length>0){  
CKEDITOR.replace('edit-editor-content',{
  customConfig: '/public/ckeditor'
});
 }
        $("#datepicker").datepicker({
            changeMonth: true,
            changeYear: true,
            yearRange: '-100:+0'
        });
        
    });
</script>
<script type="text/javascript">
    
    
    
    
  $(function () {
    var token = $('meta[name="csrf-token"]').attr('content');
  



	


                 
    //Initialize Select2 Elements
    $(".select2").select2();
    //Date range picker

   
    



/*

    //iCheck for checkbox and radio inputs
    $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
      checkboxClass: 'icheckbox_minimal-blue',
      radioClass: 'iradio_minimal-blue'
    });
    //Red color scheme for iCheck
    $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
      checkboxClass: 'icheckbox_minimal-red',
      radioClass: 'iradio_minimal-red'
    });
    //Flat red color scheme for iCheck
    $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
      checkboxClass: 'icheckbox_flat-green',
      radioClass: 'iradio_flat-green'
    });
*/


  });
</script>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

resources/views/includes/admin/header.blade.php
 <div class="loading-cntant" >
		<div class="loader"></div>
	</div>
<header class="main-header">
    <!-- Logo -->
    <a href="{{route('admin.dashboard.index')}}" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><img src="{{ asset('img/favicon.png') }}" title="{{config('settings.CONFIG_SITE_TITLE')}}"/> </span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><img src="{{ asset('img/logo.png') }}" title="{{config('settings.CONFIG_SITE_TITLE')}}"/> </span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          
           <?php $admin = adminUser();

            
             ?>
          <li class="">
           {!! HTML::link(route('admin.profile'), ucfirst($admin->first_name.' '.$admin->last_name), array('class' => '')) !!}
          </li>
            <li class="">
           {!! HTML::link(route('admin.logout'), 'Sign out', array('class' => '')) !!}
          </li>
          <li class="dropdown user user-menu">
           {!! HTML::link(WEBSITE_URL, 'Preview', array('class' => '','target'=>'_blank')) !!}
          </li>
         
        </ul>
      </div>
    </nav>
  </header>

resources/views/includes/admin/message.blade.php
@if(Session::has('alert-sucess'))

<script type="text/javascript">
	showSuccessMessageBottomRight("{!! Session::get('alert-sucess') !!}");
</script>

@endif
@if(Session::has('alert-error'))

<script type="text/javascript">
	showErrorMessageBottomRight("{!! Session::get('alert-error') !!}");
</script>

@endif

resources/views/includes/admin/sidebar.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    


     <?php 
        $rote_name =  Request::route()->getName();
     ?>

    
       <ul class="sidebar-menu">
      <li class="header">MAIN NAVIGATION</li>
   @foreach ($admin_menus as $admin_menu)
                      
        @if(empty($admin_menu['child_list']))


            <li class=" treeview  {{($rote_name==$admin_menu['route'])?'active':''}}">
        <a href="{{ ($admin_menu['route']!='')?route($admin_menu['route']):'#' }}">
          <i class="fa {{ $admin_menu['icon'] }}"></i> <span>{{ $admin_menu['name'] }}</span>
        </a>
      </li>
@else
  <?php 
        $active_class = '';
         foreach ($admin_menu['child_list'] as $child_list){
            if($rote_name==$child_list['route']){
                $active_class = 'active';
                break;
            }

         }

  ?>
  

      <li class="treeview {{$active_class}}">
        <a href="#">
          <i class="fa {{ $admin_menu['icon'] }}"></i>
         <span>{{ $admin_menu['name'] }}</span>
          <i class="fa fa-angle-left pull-right"></i>
              <ul class="treeview-menu">
                  
                   @foreach ($admin_menu['child_list'] as $child_list)
          
  <li class=" {{($rote_name==$child_list['route'])?'active':''}} "><a href="{{ ($child_list['route']!='')?route($child_list['route']):'#' }}"">
            <i class="fa {{ $child_list['icon'] }}"></i>{{ $child_list['name'] }} </a></li>
                    @endforeach 


    
                
            </ul>
        </a>
      </li>                                
          
@endif

      @endforeach 
     </ul>
  </section>
  <!-- /.sidebar -->
</aside>